"""removed user

Revision ID: 4593c05acc1c
Revises: d791ad6dd5bd
Create Date: 2023-12-07 09:24:43.498725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4593c05acc1c'
down_revision = 'd791ad6dd5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sa.VARCHAR(), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=True)
    )
    # ### end Alembic commands ###
