"""removed stockitem fields

Revision ID: 4bb472c38a54
Revises: ef4785dc0e4d
Create Date: 2023-12-07 12:53:18.996274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bb472c38a54'
down_revision = 'ef4785dc0e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.drop_column('diff')
        batch_op.drop_column('required')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('required', sa.DOUBLE(), nullable=True))
        batch_op.add_column(sa.Column('diff', sa.DOUBLE(), nullable=True))

    # ### end Alembic commands ###
