"""added user

Revision ID: 913319d163e6
Revises: bdd176d1f8bf
Create Date: 2023-12-07 08:32:07.493463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '913319d163e6'
down_revision = 'bdd176d1f8bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
